@echo off
chcp 65001 >nul
title Proxy Server Quick Setup Wizard
color 0B
cd /d "%~dp0"
cls

echo ========================================
echo    Proxy Server Quick Setup Wizard
echo ========================================
echo.

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python not found!
    echo Please install Python 3.8+ from https://www.python.org/downloads/
    pause
    exit /b 1
)

echo [1/5] Python check passed
python --version
echo.

REM Query configuration
echo ========================================
echo Please answer the following questions to configure the proxy server
echo ========================================
echo.

set /p PORT=Enter proxy port (default 8080):
if "%PORT%"=="" set PORT=8080

set /p USERNAME=Enter auth username (default admin):
if "%USERNAME%"=="" set USERNAME=admin

set /p PASSWORD=Enter auth password (strong password recommended):
if "%PASSWORD%"=="" (
    echo [ERROR] Password cannot be empty!
    pause
    exit /b 1
)

echo.
echo [WARN] Ensure password strength (length 12+, upper/lower/digits/symbols)
echo.

set /p CONFIRM=Confirm and create configuration file? (Y/n):
if /i not "%CONFIRM%"=="Y" if /i not "%CONFIRM%"=="y" (
    echo Cancelled
    pause
    exit /b 0
)

REM Generate configuration file
echo.
echo [2/5] Generating configuration file...
(
echo # Proxy server configuration
echo # Generated by Quick Setup Wizard
echo 
echo host: 0.0.0.0
echo port: %PORT%
echo 
echo auth_enabled: true
echo username: %USERNAME%
echo password: %PASSWORD%
echo 
echo log_level: INFO
) > ..\config.yaml

if exist ..\config.yaml (
    echo Configuration file created: ..\config.yaml
) else (
    echo [ERROR] Configuration file creation failed
    pause
    exit /b 1
)

REM Install dependencies
echo.
echo [3/5] Installing dependencies...
pip install -r ..\requirements.txt
if errorlevel 1 (
    echo [ERROR] Dependency installation failed
    pause
    exit /b 1
)
echo Dependencies installed.

REM Create startup shortcut
echo.
echo [4/5] Creating shortcut...
echo @echo off > ..\start-proxy.bat
echo cd /d "%~dp0" >> ..\start-proxy.bat
echo python ..\proxy_server.py %%* >> ..\start-proxy.bat
echo Created: start-proxy.bat

REM Display summary
echo.
echo ========================================
echo         Configuration Complete!
echo ========================================
echo.
echo Proxy Server Settings:
echo -------------------------
echo Port: %PORT%
echo Username: %USERNAME%
echo Password: %PASSWORD%
echo Config file: config.yaml
echo.
echo Next Steps:
echo -------------------------
echo 1. Run start.bat or start-proxy.bat to start the server
echo 2. Configure browser SwitchyOmega proxy settings:
echo    Server: 127.0.0.1 or your local IP
echo    Port: %PORT%
echo    Auth: Enabled
echo    Username: %USERNAME%
echo    Password: %PASSWORD%
echo.
echo 3. For other devices, set host to 0.0.0.0 and ensure firewall allows the port
echo.
echo Notes:
echo - Keep your password safe, do not share it
echo - Change passwords regularly
echo - For public access, enable authentication and restrict IPs
echo.
pause